### ISSUE TITLE
Underscore dependency

### ISSUE THREAD

**Issue by benstr** [stevezhu/meteor-lodash#3]
I found if underscore is not explicitly added to the app (`$ meteor add underscore`) this package does not work.

**Comment by stevezhu** [comment]
Is there some kind of error?

**Comment by benstr** [comment]
In my template helpers I call `_.some(...),` and get the following console error:

```
Exception in template helper: TypeError: undefined is not a function
    at http://localhost:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:286:40
    at _.each._.forEach (http://localhost:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:164:22)
    at Function._.some._.any (http://localhost:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:285:5)
.......
```

Using `lodash.some(...);` or adding `_ = lodash;` to the top of the file, everything works as expected.

**Comment by stevezhu** [comment]
Are you using v3.5.0? I think that was a bug I had in earlier versions.

**Comment by benstr** [comment]
Bummer, yeah my version file shows `stevezhu:lodash@3.5.0`

**Comment by stevezhu** [comment]
Hm that's strange I have clean meteor test app and it works perfectly. If you don't mind could you try creating a clean meteor app and seeing if it works there; the problem may be because of something else.

**Comment by stevezhu** [comment]
Nevermind, I see that _ and lodash aren't equal in an app even though they are equal when used in a package. Looking into it right now.

**Comment by stevezhu** [comment]
Right so a lot of meteor core packages use underscore so it seems that in an app, even though I export `_` as lodash, it is still replaced by underscore, so until meteor decides to adopt lodash you probably do have to have `_ = lodash;` at least in your first loaded javascript file.

**Comment by benstr** [comment]
Makes sense. Lets add that to the Readme.

Thanks for checking it out.

**Comment by benstr** [comment]
Nice!

**Comment by benstr** [comment]
Here is your example app modified to show the error, for reference I guess....
https://github.com/benstr/test_lodash

**Comment by stevezhu** [comment]
Thanks. Yeah, lodash is just replaced by underscore there and underscore doesn't have the includes function. =[

**Comment by rclai** [comment]
Is there a way to hijack the underscore package by creating a local version of it and replacing the code to use lodash? Has anyone tried this?
