### ISSUE TITLE
_.VERSION shows 2.4.1

### ISSUE THREAD

**Issue by Anima-t3d** [stevezhu/meteor-lodash#6]
Why is it that when I:
```javascript
_ = lodash;
console.log('version',_.VERSION);
console.log('version',lodash.VERSION);
```
It returns: `version 2.4.1`

Although the lodash.js file shows:
`var VERSION = '3.10.1';`
https://github.com/stevezhu/meteor-lodash/blob/master/lodash.js#L16

**Comment by stevezhu** [comment]
I'm not sure; it shows up correctly for me as 3.10.1. Try deleting ~/.meteor/stevezhu_lodash or the windows equivalent and running the app again.

**Comment by Anima-t3d** [comment]
Running a meteor update shows:
```console
Newer versions of the following indirect dependencies are available:
 * stevezhu:lodash 0.1.0 (3.10.1 is available)
```

The issue was due to meteor not actually using the latest version. After update it uses the correct lodash version.

In my package I had to use (I did not have the @3.10.1 before):
```javascript
api.use([
	'stevezhu:lodash@3.10.1'
]);
```

**Comment by Domiii** [comment]
I had the same problem. `_.VERSION` yielded `1.5.2`. Turns out it's because my `init` file was not called first as it should, overriding underscore with lodash. Sigh... these stupid Meteor load heuristics...... Not sure what to do about those...
